#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/starqltechn

PRODUCT_COPY_FILES += \
    vendor/samsung/starqltechn/proprietary/etc/permissions/com.qti.location.sdk.xml:$(TARGET_COPY_OUT_ETC)/permissions/com.qti.location.sdk.xml \
    vendor/samsung/starqltechn/proprietary/etc/permissions/com.qualcomm.location.xml:$(TARGET_COPY_OUT_ETC)/permissions/com.qualcomm.location.xml \
    vendor/samsung/starqltechn/proprietary/etc/permissions/izat.xt.srv.xml:$(TARGET_COPY_OUT_ETC)/permissions/izat.xt.srv.xml \
    vendor/samsung/starqltechn/proprietary/etc/permissions/privapp-permissions-com.qualcomm.location.xml:$(TARGET_COPY_OUT_ETC)/permissions/privapp-permissions-com.qualcomm.location.xml \
    vendor/samsung/starqltechn/proprietary/etc/permissions/qti_telephony_hidl_wrapper.xml:$(TARGET_COPY_OUT_ETC)/permissions/qti_telephony_hidl_wrapper.xml \
    vendor/samsung/starqltechn/proprietary/etc/permissions/qti_telephony_utils.xml:$(TARGET_COPY_OUT_ETC)/permissions/qti_telephony_utils.xml \
    vendor/samsung/starqltechn/proprietary/product/etc/permissions/vendor.qti.hardware.data.connection-V1.1-java.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/vendor.qti.hardware.data.connection-V1.1-java.xml \
    vendor/samsung/starqltechn/proprietary/vendor/app/mcRegistry/07010000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/samsung/starqltechn/proprietary/vendor/app/mcRegistry/ffffffffd00000000000000000000014.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffffd00000000000000000000014.tlbin \
    vendor/samsung/starqltechn/proprietary/vendor/etc/SoundBoosterParam.txt:$(TARGET_COPY_OUT_VENDOR)/etc/SoundBoosterParam.txt \
    vendor/samsung/starqltechn/proprietary/vendor/etc/audconf/OPEN/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Bluetooth_cal.acdb \
    vendor/samsung/starqltechn/proprietary/vendor/etc/audconf/OPEN/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Codec_cal.acdb \
    vendor/samsung/starqltechn/proprietary/vendor/etc/audconf/OPEN/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/General_cal.acdb \
    vendor/samsung/starqltechn/proprietary/vendor/etc/audconf/OPEN/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Global_cal.acdb \
    vendor/samsung/starqltechn/proprietary/vendor/etc/audconf/OPEN/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Handset_cal.acdb \
    vendor/samsung/starqltechn/proprietary/vendor/etc/audconf/OPEN/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Hdmi_cal.acdb \
    vendor/samsung/starqltechn/proprietary/vendor/etc/audconf/OPEN/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Headset_cal.acdb \
    vendor/samsung/starqltechn/proprietary/vendor/etc/audconf/OPEN/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Speaker_cal.acdb \
    vendor/samsung/starqltechn/proprietary/vendor/etc/audconf/OPEN/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/workspaceFile.qwsp \
    vendor/samsung/starqltechn/proprietary/vendor/etc/cacert_location.pem:$(TARGET_COPY_OUT_VENDOR)/etc/cacert_location.pem \
    vendor/samsung/starqltechn/proprietary/vendor/etc/camera/imx258tuned.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx258tuned.bin \
    vendor/samsung/starqltechn/proprietary/vendor/etc/configstore/vpp.configstore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/configstore/vpp.configstore.xml \
    vendor/samsung/starqltechn/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/samsung/starqltechn/proprietary/vendor/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    vendor/samsung/starqltechn/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/samsung/starqltechn/proprietary/vendor/etc/floating_feature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/floating_feature.xml \
    vendor/samsung/starqltechn/proprietary/vendor/etc/gpfspath_oem_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gpfspath_oem_config.xml \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/android.hardware.atrace@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.atrace@1.0-service.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/android.hardware.audio@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.audio@2.0-service.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/android.hardware.drm@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.0-service.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/android.hardware.drm@1.2-service.clearkey.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.2-service.clearkey.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/android.hardware.drm@1.2-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.2-service.widevine.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/android.hardware.gnss@2.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss@2.0-service-qti.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/android.hardware.graphics.composer@2.3-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.composer@2.3-service.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/android.hardware.health@2.0-service.samsung.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.health@2.0-service.samsung.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/android.hardware.keymaster@3.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@3.0-service.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/android.hardware.memtrack@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.memtrack@1.0-service.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/android.hardware.neuralnetworks@1.2-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks@1.2-service-qti.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/android.hardware.thermal@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.thermal@1.0-service.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/android.hardware.vr@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.vr@1.0-service.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/dataadpl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataadpl.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/hw/init.samsung.bsp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.samsung.bsp.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/hw/init.samsung.display.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.samsung.display.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/hw/init.samsung.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.samsung.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/init-qcril-data.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init-qcril-data.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/init.time_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.time_daemon.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/init.vendor.onebinary.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.onebinary.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/init.vendor.rilchip.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.rilchip.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/init.vendor.rilcommon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.rilcommon.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/ipa_fws.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipa_fws.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/ipacm-diag.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipacm-diag.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/ipacm.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipacm.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/netmgrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netmgrd.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/pa_daemon_qsee.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/pa_daemon_qsee.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/qdcmss.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qdcmss.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/qseecomd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qseecomd.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/snap_utility.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/snap_utility.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/vendor.display.color@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.display.color@1.0-service.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/vendor.qti.adsprpc-guestos-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.adsprpc-guestos-service.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/vendor.qti.hardware.cryptfshw@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.cryptfshw@1.0-service-qti.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/vendor.qti.hardware.cvp@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.cvp@1.0-service.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/vendor.qti.hardware.display.allocator@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.display.allocator@1.0-service.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/vendor.qti.hardware.iop@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.iop@2.0-service.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/vendor.qti.hardware.perf@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.perf@2.0-service.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/vendor.qti.hardware.qdutils_disp@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qdutils_disp@1.0-service-qti.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/vendor.trustonic.tee@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.trustonic.tee@1.0-service.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/vendor.trustonic.teeregistry@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.trustonic.teeregistry@1.0-service.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/vppservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vppservice.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/wifi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wifi.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/init/wifi_brcm.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wifi_brcm.rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/samsung/starqltechn/proprietary/vendor/etc/locale/plmn_delta_eng.bin:$(TARGET_COPY_OUT_VENDOR)/etc/locale/plmn_delta_eng.bin \
    vendor/samsung/starqltechn/proprietary/vendor/etc/locale/plmn_delta_zh-rCN.bin:$(TARGET_COPY_OUT_VENDOR)/etc/locale/plmn_delta_zh-rCN.bin \
    vendor/samsung/starqltechn/proprietary/vendor/etc/locale/plmn_delta_zh-rHK.bin:$(TARGET_COPY_OUT_VENDOR)/etc/locale/plmn_delta_zh-rHK.bin \
    vendor/samsung/starqltechn/proprietary/vendor/etc/locale/plmn_delta_zh-rTW.bin:$(TARGET_COPY_OUT_VENDOR)/etc/locale/plmn_delta_zh-rTW.bin \
    vendor/samsung/starqltechn/proprietary/vendor/etc/media_codecs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs.xml \
    vendor/samsung/starqltechn/proprietary/vendor/etc/media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_dolby_audio.xml \
    vendor/samsung/starqltechn/proprietary/vendor/etc/media_codecs_performance.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance.xml \
    vendor/samsung/starqltechn/proprietary/vendor/etc/media_profiles.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles.xml \
    vendor/samsung/starqltechn/proprietary/vendor/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml \
    vendor/samsung/starqltechn/proprietary/vendor/etc/media_profiles_vendor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_vendor.xml \
    vendor/samsung/starqltechn/proprietary/vendor/etc/mtu-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mtu-conf.xml \
    vendor/samsung/starqltechn/proprietary/vendor/etc/nfc/sec_s3nrn82_rfreg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nfc/sec_s3nrn82_rfreg.bin \
    vendor/samsung/starqltechn/proprietary/vendor/etc/pdpcnt-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pdpcnt-conf.xml \
    vendor/samsung/starqltechn/proprietary/vendor/etc/perf/commonresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/commonresourceconfigs.xml \
    vendor/samsung/starqltechn/proprietary/vendor/etc/perf/perf-profile0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perf-profile0.conf \
    vendor/samsung/starqltechn/proprietary/vendor/etc/perf/perf-profile1.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perf-profile1.conf \
    vendor/samsung/starqltechn/proprietary/vendor/etc/perf/perf-profile2.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perf-profile2.conf \
    vendor/samsung/starqltechn/proprietary/vendor/etc/perf/perf-profile3.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perf-profile3.conf \
    vendor/samsung/starqltechn/proprietary/vendor/etc/perf/perf-profile4.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perf-profile4.conf \
    vendor/samsung/starqltechn/proprietary/vendor/etc/perf/perf-profile5.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perf-profile5.conf \
    vendor/samsung/starqltechn/proprietary/vendor/etc/perf/perf-profile6.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perf-profile6.conf \
    vendor/samsung/starqltechn/proprietary/vendor/etc/perf/perfboostsconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfboostsconfig.xml \
    vendor/samsung/starqltechn/proprietary/vendor/etc/perf/perfconfigstore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfconfigstore.xml \
    vendor/samsung/starqltechn/proprietary/vendor/etc/perf/targetconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetconfig.xml \
    vendor/samsung/starqltechn/proprietary/vendor/etc/perf/targetresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetresourceconfigs.xml \
    vendor/samsung/starqltechn/proprietary/vendor/etc/playback_record_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/playback_record_audio_policy_configuration.xml \
    vendor/samsung/starqltechn/proprietary/vendor/etc/plmn_delta_hktw.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_hktw.bin \
    vendor/samsung/starqltechn/proprietary/vendor/etc/plmn_se13.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_se13.bin \
    vendor/samsung/starqltechn/proprietary/vendor/etc/powerhint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/powerhint.xml \
    vendor/samsung/starqltechn/proprietary/vendor/etc/process_authenticator/pa_config:$(TARGET_COPY_OUT_VENDOR)/etc/process_authenticator/pa_config \
    vendor/samsung/starqltechn/proprietary/vendor/etc/public.libraries.txt.backup:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt.backup \
    vendor/samsung/starqltechn/proprietary/vendor/etc/qdcm_calib_data_ss_dsi_panel_S6E3HA8_AMB577PX01_WQHD.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_ss_dsi_panel_S6E3HA8_AMB577PX01_WQHD.xml \
    vendor/samsung/starqltechn/proprietary/vendor/etc/saiv/fd/fast_face_detect_model_full_angle_16_CHAR.dat:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/fd/fast_face_detect_model_full_angle_16_CHAR.dat \
    vendor/samsung/starqltechn/proprietary/vendor/etc/saiv/gae/MeanFea.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/MeanFea.bin \
    vendor/samsung/starqltechn/proprietary/vendor/etc/saiv/gae/ParaFea.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/ParaFea.bin \
    vendor/samsung/starqltechn/proprietary/vendor/etc/saiv/gae/PmAgeFeatSelIdx.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/PmAgeFeatSelIdx.bin \
    vendor/samsung/starqltechn/proprietary/vendor/etc/saiv/gae/PmAgeModel.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/PmAgeModel.bin \
    vendor/samsung/starqltechn/proprietary/vendor/etc/saiv/gae/PmExpFeatSelIdx.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/PmExpFeatSelIdx.bin \
    vendor/samsung/starqltechn/proprietary/vendor/etc/saiv/gae/PmExpModel.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/PmExpModel.bin \
    vendor/samsung/starqltechn/proprietary/vendor/etc/saiv/gae/PmGenModel.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/PmGenModel.bin \
    vendor/samsung/starqltechn/proprietary/vendor/etc/saiv/gae/PmGenderFeatSelIdx.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/PmGenderFeatSelIdx.bin \
    vendor/samsung/starqltechn/proprietary/vendor/etc/saiv/ld/avg_hog_13pt.dat:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/ld/avg_hog_13pt.dat \
    vendor/samsung/starqltechn/proprietary/vendor/etc/saiv/ld/avg_hog_35pt.dat:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/ld/avg_hog_35pt.dat \
    vendor/samsung/starqltechn/proprietary/vendor/etc/saiv/ld/mean_35pt.txt:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/ld/mean_35pt.txt \
    vendor/samsung/starqltechn/proprietary/vendor/etc/saiv/ld/regress_matrix_short_13pt.dat:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/ld/regress_matrix_short_13pt.dat \
    vendor/samsung/starqltechn/proprietary/vendor/etc/saiv/ld/regress_matrix_short_35pt.dat:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/ld/regress_matrix_short_35pt.dat \
    vendor/samsung/starqltechn/proprietary/vendor/etc/sec_config:$(TARGET_COPY_OUT_VENDOR)/etc/sec_config \
    vendor/samsung/starqltechn/proprietary/vendor/etc/sec_config_oem:$(TARGET_COPY_OUT_VENDOR)/etc/sec_config_oem \
    vendor/samsung/starqltechn/proprietary/vendor/etc/sensors/config/ak991x_dri_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ak991x_dri_0.json \
    vendor/samsung/starqltechn/proprietary/vendor/etc/sensors/config/lsm6dsm_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lsm6dsm_0.json \
    vendor/samsung/starqltechn/proprietary/vendor/etc/sensors/config/sdm845_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_ak991x_0.json \
    vendor/samsung/starqltechn/proprietary/vendor/etc/sensors/config/sdm845_ak991x_2.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_ak991x_2.json \
    vendor/samsung/starqltechn/proprietary/vendor/etc/sensors/config/sdm845_lps22hb_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_lps22hb_0.json \
    vendor/samsung/starqltechn/proprietary/vendor/etc/sensors/config/sdm845_lsm6dsm_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_lsm6dsm_0.json \
    vendor/samsung/starqltechn/proprietary/vendor/etc/sensors/config/sdm845_lsm6dsm_2.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_lsm6dsm_2.json \
    vendor/samsung/starqltechn/proprietary/vendor/etc/sensors/config/sdm845_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_power_0.json \
    vendor/samsung/starqltechn/proprietary/vendor/etc/sensors/config/sdm845_tmd4906_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_tmd4906_0.json \
    vendor/samsung/starqltechn/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/samsung/starqltechn/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/samsung/starqltechn/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/samsung/starqltechn/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    vendor/samsung/starqltechn/proprietary/vendor/etc/sensors/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_geomag_rv.json \
    vendor/samsung/starqltechn/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/samsung/starqltechn/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/samsung/starqltechn/proprietary/vendor/etc/sensors/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rmd.json \
    vendor/samsung/starqltechn/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/samsung/starqltechn/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/samsung/starqltechn/proprietary/vendor/etc/snap_gpu_kernel_32.bin:$(TARGET_COPY_OUT_VENDOR)/etc/snap_gpu_kernel_32.bin \
    vendor/samsung/starqltechn/proprietary/vendor/etc/snap_gpu_kernel_64.bin:$(TARGET_COPY_OUT_VENDOR)/etc/snap_gpu_kernel_64.bin \
    vendor/samsung/starqltechn/proprietary/vendor/etc/somxreg.conf:$(TARGET_COPY_OUT_VENDOR)/etc/somxreg.conf \
    vendor/samsung/starqltechn/proprietary/vendor/etc/ssg/ta_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/ta_config.json \
    vendor/samsung/starqltechn/proprietary/vendor/etc/ssg/tz_whitelist.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/tz_whitelist.json \
    vendor/samsung/starqltechn/proprietary/vendor/etc/str/str_preference_data.dat:$(TARGET_COPY_OUT_VENDOR)/etc/str/str_preference_data.dat \
    vendor/samsung/starqltechn/proprietary/vendor/etc/system_properties.xml:$(TARGET_COPY_OUT_VENDOR)/etc/system_properties.xml \
    vendor/samsung/starqltechn/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/samsung/starqltechn/proprietary/vendor/etc/tms_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/tms_audio_policy_configuration.xml \
    vendor/samsung/starqltechn/proprietary/vendor/etc/wifi/bcmdhd_clm.blob:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_clm.blob \
    vendor/samsung/starqltechn/proprietary/vendor/etc/wifi/bcmdhd_mfg.bin_b0:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_mfg.bin_b0 \
    vendor/samsung/starqltechn/proprietary/vendor/etc/wifi/bcmdhd_mfg.bin_b2:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_mfg.bin_b2 \
    vendor/samsung/starqltechn/proprietary/vendor/etc/wifi/bcmdhd_mon.bin_b2:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_mon.bin_b2 \
    vendor/samsung/starqltechn/proprietary/vendor/etc/wifi/bcmdhd_sta.bin_b0:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_sta.bin_b0 \
    vendor/samsung/starqltechn/proprietary/vendor/etc/wifi/bcmdhd_sta.bin_b2:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_sta.bin_b2 \
    vendor/samsung/starqltechn/proprietary/vendor/etc/wifi/nvram.txt_murata_r020_b2:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram.txt_murata_r020_b2 \
    vendor/samsung/starqltechn/proprietary/vendor/etc/wifi/nvram.txt_murata_r021_b2:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram.txt_murata_r021_b2 \
    vendor/samsung/starqltechn/proprietary/vendor/etc/wifi/nvram.txt_murata_r022_b2:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram.txt_murata_r022_b2 \
    vendor/samsung/starqltechn/proprietary/vendor/etc/wifi/nvram.txt_murata_r031_b2:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram.txt_murata_r031_b2 \
    vendor/samsung/starqltechn/proprietary/vendor/etc/wifi/nvram.txt_murata_r033_b0:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram.txt_murata_r033_b0 \
    vendor/samsung/starqltechn/proprietary/vendor/etc/wifi/nvram.txt_murata_r041_b2:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram.txt_murata_r041_b2 \
    vendor/samsung/starqltechn/proprietary/vendor/etc/wlan_common_rc:$(TARGET_COPY_OUT_VENDOR)/etc/wlan_common_rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/wlan_vendor_rc:$(TARGET_COPY_OUT_VENDOR)/etc/wlan_vendor_rc \
    vendor/samsung/starqltechn/proprietary/vendor/etc/xtra_root_cert.pem:$(TARGET_COPY_OUT_VENDOR)/etc/xtra_root_cert.pem \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/CAMERA_ICP.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.elf \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/a225_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a225_pfp.fw \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/a225_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a225_pm4.fw \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/a225p5_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a225p5_pm4.fw \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/a300_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a300_pfp.fw \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/a300_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a300_pm4.fw \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/a330_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a330_pfp.fw \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/a330_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a330_pm4.fw \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/a420_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a420_pfp.fw \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/a420_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a420_pm4.fw \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/a530_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_gpmu.fw2 \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/a530v1_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v1_pfp.fw \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/a530v1_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v1_pm4.fw \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/a530v2_seq.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v2_seq.fw2 \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/a530v3_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v3_gpmu.fw2 \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/a530v3_seq.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v3_seq.fw2 \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/a540_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_gpmu.fw2 \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/a630_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_gmu.bin \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/a630_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_sqe.fw \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/bcm4361B2_murata.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4361B2_murata.hcd \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/bcm4361B2_semco.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4361B2_semco.hcd \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/ipa_fws.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b00 \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/ipa_fws.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b01 \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/ipa_fws.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b02 \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/ipa_fws.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b03 \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/ipa_fws.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b04 \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/ipa_fws.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.elf \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/ipa_fws.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.mdt \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/leia_pfp_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pfp_470.fw \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/leia_pm4_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pm4_470.fw \
    vendor/samsung/starqltechn/proprietary/vendor/firmware/nfc/sec_s3nrn82_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nfc/sec_s3nrn82_firmware.bin \
    vendor/samsung/starqltechn/proprietary/vendor/lib/camera/com.qti.sensormodule.0_imx345.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.0_imx345.bin \
    vendor/samsung/starqltechn/proprietary/vendor/lib/camera/com.qti.sensormodule.1_imx320.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.1_imx320.bin \
    vendor/samsung/starqltechn/proprietary/vendor/lib/camera/com.qti.sensormodule.2_s5k5f1sx.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.2_s5k5f1sx.bin \
    vendor/samsung/starqltechn/proprietary/vendor/lib/camera/com.qti.sensormodule.4_imx320_full.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.4_imx320_full.bin \
    vendor/samsung/starqltechn/proprietary/vendor/lib/camera/eebindriver.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/eebindriver.bin \
    vendor/samsung/starqltechn/proprietary/vendor/lib/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigpreview.bin \
    vendor/samsung/starqltechn/proprietary/vendor/lib/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigvideo.bin \
    vendor/samsung/starqltechn/proprietary/vendor/lib/camera/imx320tuned.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/imx320tuned.bin \
    vendor/samsung/starqltechn/proprietary/vendor/lib/camera/imx345tuned.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/imx345tuned.bin \
    vendor/samsung/starqltechn/proprietary/vendor/lib/camera/ois_fw_dom.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/ois_fw_dom.bin \
    vendor/samsung/starqltechn/proprietary/vendor/lib/camera/ois_fw_sec.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/ois_fw_sec.bin \
    vendor/samsung/starqltechn/proprietary/vendor/lib/camera/s5k5f1sxtuned.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/s5k5f1sxtuned.bin \
    vendor/samsung/starqltechn/proprietary/vendor/lib/camera/systemdefault.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/systemdefault.bin \
    vendor/samsung/starqltechn/proprietary/vendor/lib/camera/titan17x_usecases.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/titan17x_usecases.bin \
    vendor/samsung/starqltechn/proprietary/vendor/saiv/image_understanding/db/aic_classifier/aic_classifier_cnn.prototxt:$(TARGET_COPY_OUT_VENDOR)/saiv/image_understanding/db/aic_classifier/aic_classifier_cnn.prototxt \
    vendor/samsung/starqltechn/proprietary/vendor/saiv/image_understanding/db/aic_classifier/aic_classifier_cnn_light.caffemodel:$(TARGET_COPY_OUT_VENDOR)/saiv/image_understanding/db/aic_classifier/aic_classifier_cnn_light.caffemodel \
    vendor/samsung/starqltechn/proprietary/vendor/saiv/image_understanding/db/aic_detector/aic_detector_cnn.prototxt:$(TARGET_COPY_OUT_VENDOR)/saiv/image_understanding/db/aic_detector/aic_detector_cnn.prototxt \
    vendor/samsung/starqltechn/proprietary/vendor/saiv/image_understanding/db/aic_detector/aic_detector_cnn_light.caffemodel:$(TARGET_COPY_OUT_VENDOR)/saiv/image_understanding/db/aic_detector/aic_detector_cnn_light.caffemodel \
    vendor/samsung/starqltechn/proprietary/vendor/saiv/image_understanding/db/aig_classifier/aig_classifier_cnn.prototxt:$(TARGET_COPY_OUT_VENDOR)/saiv/image_understanding/db/aig_classifier/aig_classifier_cnn.prototxt \
    vendor/samsung/starqltechn/proprietary/vendor/saiv/image_understanding/db/aig_classifier/aig_classifier_cnn_light.caffemodel:$(TARGET_COPY_OUT_VENDOR)/saiv/image_understanding/db/aig_classifier/aig_classifier_cnn_light.caffemodel \
    vendor/samsung/starqltechn/proprietary/vendor/saiv/image_understanding/db/aig_detector/aig_detector_cnn.prototxt:$(TARGET_COPY_OUT_VENDOR)/saiv/image_understanding/db/aig_detector/aig_detector_cnn.prototxt \
    vendor/samsung/starqltechn/proprietary/vendor/saiv/image_understanding/db/aig_detector/aig_detector_cnn_light.caffemodel:$(TARGET_COPY_OUT_VENDOR)/saiv/image_understanding/db/aig_detector/aig_detector_cnn_light.caffemodel

PRODUCT_PACKAGES += \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.stats.aec \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qualcomm.qti.imscmservice@1.0 \
    com.qualcomm.qti.imscmservice@2.0 \
    com.qualcomm.qti.imscmservice@2.1 \
    com.qualcomm.qti.imscmservice@2.2 \
    com.qualcomm.qti.uceservice@2.0 \
    com.qualcomm.qti.uceservice@2.1 \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libQTapGLES \
    libq3dtools_adreno \
    libq3dtools_esx \
    ftm_fm_lib \
    android.hardware.audio.effect@2.0-impl \
    android.hardware.gnss@2.0-impl-qti \
    android.hardware.graphics.mapper@2.0-impl-qti-display \
    android.hardware.vr@1.0-impl \
    audio.primary.default \
    audio.r_submix.default \
    audio.sec_primary.default \
    audio.usb.default \
    fingerprint.default \
    gralloc.default \
    gralloc.sdm845 \
    hwcomposer.sdm845 \
    lights.sdm845 \
    memtrack.sdm845 \
    sound_trigger.primary.sdm845 \
    thermal.sdm845 \
    vendor.qti.gnss@3.0-impl \
    vendor.qti.hardware.cvp@1.0-impl \
    vendor.qti.hardware.iop@2.0-impl \
    vendor.qti.hardware.qseecom@1.0-impl \
    vendor.samsung.hardware.audio@1.0-impl \
    vendor.samsung.hardware.gnss@2.0-impl-sec \
    vibrator.default \
    vr.sdm845 \
    vulkan.sdm845 \
    libAlacSwDec \
    libApeSwDec \
    libC2D2 \
    libCB \
    libDLInterface.camera.samsung \
    libFlacSwDec \
    libGPTEE_vendor \
    libGPreqcancel \
    libGPreqcancel_svc \
    libHMT \
    libI420colorconvert \
    libIDDQD_core \
    libIDDQD_interface \
    libMcClient \
    libMpeg4SwEncoder \
    libOmxAacDec \
    libOmxAacEnc \
    libOmxAlacDec \
    libOmxAlacDecSw \
    libOmxAmrDec \
    libOmxAmrEnc \
    libOmxAmrwbplusDec \
    libOmxApeDec \
    libOmxApeDecSw \
    libOmxBlackBar \
    libOmxCore \
    libOmxEvrcDec \
    libOmxEvrcEnc \
    libOmxG711Dec \
    libOmxG711Enc \
    libOmxQcelp13Dec \
    libOmxQcelp13Enc \
    libOmxSwVdec \
    libOmxSwVencMpeg4 \
    libOmxVdec \
    libOmxVenc \
    libOmxVpp \
    libOmxWmaDec \
    libOpenCL \
    libOpenCv.camera.samsung \
    libQSEEComAPI \
    libRSDriver_adreno \
    libSecureUILib \
    libStDrvInt \
    libSubSystemShutdown \
    libTigerCaV4 \
    libTigerLogger \
    lib_SoundAlive_3DPosition_ver202 \
    lib_SoundAlive_AlbumArt_ver105 \
    lib_SoundAlive_play_plus_ver210 \
    lib_SoundBooster_ver900 \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libadiertac \
    libadreno_utils \
    libadsp_default_listener \
    libadsprpc \
    libarac \
    libarcsoft_super_night_raw \
    libaudcal \
    libaudioalsa \
    libaudioconfigstore \
    libaudioparsers \
    libbase64 \
    libbatching \
    libbauthserver \
    libbauthtzcommon \
    libbccQTI \
    libblurdetection \
    libblurdetection_interface \
    libc2d30_bltlib \
    libc2dcolorconvert \
    libcamera_nn_stub \
    libcamxfdalgov7 \
    libcamxfdengine \
    libcamxstatscore \
    libcamxswprocessalgo \
    libcapiv2svacnn \
    libcapiv2vop \
    libcdsp_default_listener \
    libcdsprpc \
    libconfigdb \
    libcpion \
    libcryptfshwcommon \
    libcryptfshwhidl \
    libcsd-client \
    libcvp \
    libcvp_common \
    libcvp_stub \
    libcvpcpuRev_skel \
    libdataitems \
    libdiag \
    libdiagjni \
    libdisp-aba \
    libdisplayconfig \
    libdisplaydebug \
    libdisplayqos \
    libdrm \
    libdrmfs \
    libdrmtime \
    libdrmutils \
    libdsi_netctrl \
    libdsutils \
    libegis_fp_normal_sensor_test \
    libfastcvdsp_stub \
    libfastcvopt \
    libfloatingfeature \
    libfocuspeaking \
    libfocuspeaking_interface \
    libgarden \
    libgcs-calwrapper \
    libgcs-ipc \
    libgcs-osal \
    libgcs \
    libgdtap \
    libgeofencing \
    libgf_in_system_lib \
    libgnss \
    libgnsspps \
    libgps.utils \
    libgpu_tonemapper \
    libgralloccore \
    libgrallocutils \
    libgsl \
    libhdcp1prov \
    libhdcp2p2prov \
    libhdcpsrm \
    libhdr_tm \
    libhifills \
    libhifills_interface \
    libhifistill_tuning \
    libhigh_dynamic_range \
    libhypermotion_core \
    libhypermotion_interface \
    libidl \
    libizat_client_api \
    libizat_core \
    liblbs_core \
    liblistensoundmodel2 \
    libllhdr_interface \
    libllvm-glnext \
    libllvm-qcom \
    libloc_api_v02 \
    libloc_core \
    libloc_socket \
    liblocation_api \
    liblocationservice \
    liblocationservice_glue \
    liblow_light_hdr \
    liblowi_client \
    liblowi_wifihal \
    liblqe \
    libmdf \
    libmdmdetect \
    libmdsprpc \
    libmfhdr_interface \
    libminkdescriptor \
    libmm-color-convertor \
    libmm-hdcpmgr \
    libmm-omxcore \
    libmmosal_proprietary \
    libmmparser_lite_proprietary \
    libmpbase \
    libmulawdec \
    libnetmgr \
    libnetmgr_common \
    liboemaids_vendor \
    liboemcrypto \
    libpa \
    libpadm \
    libpassese \
    libpdmapper \
    libpdnotifier \
    libperfconfig \
    libperfgluelayer \
    libperipheral_client \
    libprofileparamstorage \
    libpvr \
    libqcbor \
    libqcmaputils \
    libqdMetaData \
    libqdi \
    libqdma \
    libqdp \
    libqdutils \
    libqfp_sensortest \
    libqisl \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_encdec \
    libqmiservices \
    libqrtr \
    libqseed3 \
    libqservice \
    libqsocket \
    libqti-iopd-client \
    libqti-iopd \
    libqti-perfd-client \
    libqti-perfd \
    libqti-util \
    libqti-utils \
    libqti_vndfwk_detect \
    libqtigef \
    libril \
    librmp \
    librpmb \
    librs_adreno \
    librs_adreno_sha1 \
    libsaiv_BeautySolutionVideo \
    libsaped \
    libsavsac \
    libsavscmn \
    libsavsvc \
    libsdedrm \
    libsdm-color \
    libsdm-diag \
    libsdm-disp-vndapis \
    libsdmcore \
    libsdmextension \
    libsdmutils \
    libsdsprpc \
    libsec-ril-dsds \
    libsec-ril \
    libsec_semRil \
    libsecaudiocoreutils \
    libsecaudioinfo \
    libsecnativefeature \
    libsecureui \
    libsecureui_svcsock \
    libsemnativecarrierfeature \
    libsensorlistener \
    libsensorslog \
    libsi \
    libskeymaster3device \
    libsmartfocus_interface \
    libsmartfocusengine \
    libsnaace \
    libsnamrnb \
    libsnamrwb \
    libsnap_caffe \
    libsnap_caffe_wrapper \
    libsnap_compute \
    libsnap_compute_wrapper \
    libsnap_vndk \
    libsnaplite_native \
    libsnaplite_wrapper \
    libsns_device_mode_stub \
    libsns_fastRPC_util \
    libsns_low_lat_stream_stub \
    libsnsapi \
    libsomx263dsw \
    libsomx264dsw \
    libsomxaacd \
    libsomxadpcmd \
    libsomxamrd \
    libsomxaped \
    libsomxcmn \
    libsomxcore_vendor \
    libsomxflacd \
    libsomxhevcdsw \
    libsomxmp3d \
    libsomxmp43d \
    libsomxmp4vdsw \
    libsomxnaace \
    libsomxvc1dsw \
    libsomxvp8d \
    libsomxwmad \
    libsomxwmv7d \
    libsomxwmv8d \
    libspcom \
    libspictrl \
    libspiris \
    libspl \
    libssc \
    libssc_default_listener \
    libssd \
    libstagefright_soft_qtiflacdec \
    libstagefrighthw \
    libstr_capture_core \
    libstr_preview_core \
    libsubsystem_control \
    libswregistrationalgo \
    libswvdec \
    libsxqk \
    libsynaFpSensorTestNwd \
    libsysmon_cdsp_skel \
    libsystem_health_mon \
    libthermalclient \
    libtime_genoff \
    libtinycompress \
    libtinyxml2_1 \
    libtzdrmgenprov \
    libuniapi \
    libuniplugin \
    libvdis_core \
    libvdis_interface \
    libvideobeauty_interface \
    libvkmanager_vendor \
    libvndfwk_detect_jni.qti \
    libvndsecril-client \
    libvppclient \
    libvpphcp \
    libvpphvx \
    libvpplibrary \
    libvpptestutils \
    libxcv.camera.samsung \
    libxml \
    libxtadapter \
    sensors.bio \
    sensors.grip \
    sensors.ssc \
    libasphere \
    libaudioeffectoffload \
    libaudiosaplus_sec \
    libgearvr \
    libmysound \
    libmyspace \
    libplaybackrecorder \
    libqcbassboost \
    libqcompostprocbundle \
    libqcomvisualizer \
    libqcomvoiceprocessing \
    libqcreverb \
    libqcvirt \
    libsamsungSoundbooster_plus \
    libshoebox \
    libswdap \
    libvolumelistener \
    vendor.display.color@1.0 \
    vendor.display.color@1.1 \
    vendor.display.color@1.2 \
    vendor.display.config@1.0 \
    vendor.display.config@1.1 \
    vendor.display.config@1.2 \
    vendor.display.config@1.3 \
    vendor.display.config@1.4 \
    vendor.display.config@1.5 \
    vendor.display.config@1.6 \
    vendor.display.config@1.7 \
    vendor.display.config@1.8 \
    vendor.display.config@1.9 \
    vendor.display.postproc@1.0 \
    vendor.qti.data.factory@2.0 \
    vendor.qti.gnss@1.0 \
    vendor.qti.gnss@1.1 \
    vendor.qti.gnss@1.2 \
    vendor.qti.gnss@2.0 \
    vendor.qti.gnss@2.1 \
    vendor.qti.gnss@3.0-service \
    vendor.qti.gnss@3.0 \
    vendor.qti.hardware.automotive.vehicle@1.0 \
    vendor.qti.hardware.cacert@1.0 \
    vendor.qti.hardware.camera.device@1.0 \
    vendor.qti.hardware.cryptfshw@1.0 \
    vendor.qti.hardware.cvp@1.0-halimpl \
    vendor.qti.hardware.cvp@1.0 \
    vendor.qti.hardware.data.cne.internal.api@1.0 \
    vendor.qti.hardware.data.cne.internal.constants@1.0 \
    vendor.qti.hardware.data.cne.internal.server@1.0 \
    vendor.qti.hardware.data.connection@1.0 \
    vendor.qti.hardware.data.connection@1.1 \
    vendor.qti.hardware.data.dynamicdds@1.0 \
    vendor.qti.hardware.data.qmi@1.0 \
    vendor.qti.hardware.fingerprint@1.0 \
    vendor.qti.hardware.fm@1.0 \
    vendor.qti.hardware.iop@1.0 \
    vendor.qti.hardware.iop@2.0 \
    vendor.qti.hardware.qdutils_disp@1.0 \
    vendor.qti.hardware.qseecom@1.0 \
    vendor.qti.hardware.scve.objecttracker@1.0 \
    vendor.qti.hardware.scve.panorama@1.0 \
    vendor.qti.hardware.tui_comm@1.0 \
    vendor.qti.hardware.vpp@1.1 \
    vendor.qti.hardware.vpp@1.2 \
    vendor.qti.ims.callinfo@1.0 \
    vendor.qti.ims.rcsconfig@1.0 \
    vendor.qti.imsrtpservice@2.0 \
    vendor.qti.imsrtpservice@2.1 \
    vendor.qti.latency@2.0 \
    vendor.qti.power.pasrmanager@1.0 \
    vendor.qti.voiceprint@1.0 \
    vendor.samsung.hardware.audio@1.0 \
    vendor.samsung.hardware.gnss@2.0 \
    vendor.samsung.hardware.radio.bridge@2.0 \
    vendor.samsung.hardware.radio.channel@2.0 \
    vendor.samsung.hardware.radio@2.0 \
    vendor.samsung.hardware.radio@2.1 \
    H12QS_libTsAe \
    H12QS_libTsAf \
    H12QS_libTsAwb \
    H12QS_libTsPdafm \
    W08QS_libTsAeFront \
    W08QS_libTsAfFront \
    W08QS_libTsAwbFront \
    com.qti.sensor.imx318 \
    com.qti.sensor.imx320 \
    com.qti.sensor.imx345 \
    com.qti.sensor.s5k3m3 \
    com.qti.sensor.s5k5f1sx \
    com.qti.node.gpu \
    com.qti.node.memcpy \
    com.qti.node.str \
    com.qti.node.swregistration \
    com.samsung.node.bayerfuse \
    com.samsung.node.uniplugin_capture \
    com.samsung.node.uniplugin_preview \
    com.samsung.node.uniplugin_recording \
    com.samsung.node.uniplugin_vdis \
    com.ss.stats.aec \
    com.ss.stats.af \
    com.ss.stats.awb \
    com.ss.stats.pdlib \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.remosaic \
    audio.primary.sdm845 \
    camera.qcom \
    com.samsung.chi.override \
    libFileMux_proprietary \
    libFrucSSMLib \
    libOmxDsdDec \
    libOmxMux_proprietary \
    lib_SamsungRec_06006 \
    lib_SoundAlive_SRC384_ver320 \
    lib_soundaliveresampler \
    liba2dpoffload \
    libadm \
    libadpcmdec \
    libapex_cmn \
    libapex_utils \
    libaudio_log_utils \
    libaudio_soundtrigger \
    libbatterylistener \
    libchiss3alogdebug \
    libcirrusspkrprot \
    libcom.qti.chinodeutils \
    libcomprcapture \
    libcppf \
    libdeccfg \
    libdrc \
    libdsd2pcm \
    libdualcam_optical_zoom_control \
    libexthwplugin \
    libfastcrc \
    libgtmdrv \
    libhdmiedid \
    libhdmipassthru \
    libhfp \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmrtpdecoder_proprietary \
    libmmrtpencoder_proprietary \
    libopus \
    libpredeflicker_native \
    librecordalive \
    libsamsungVoipResampler \
    libsmwrapper \
    libsndmonitor \
    libspkrprot \
    libstagefright_bufferqueue_helper_vendor \
    libstagefright_omx_vendor \
    libstagefright_soft_aacdec \
    libstagefright_soft_aacenc \
    libstagefright_soft_ac4dec \
    libstagefright_soft_amrdec \
    libstagefright_soft_amrnbenc \
    libstagefright_soft_amrwbenc \
    libstagefright_soft_avcdec \
    libstagefright_soft_avcenc \
    libstagefright_soft_ddpdec \
    libstagefright_soft_flacdec \
    libstagefright_soft_flacenc \
    libstagefright_soft_g711dec \
    libstagefright_soft_gsmdec \
    libstagefright_soft_hevcdec \
    libstagefright_soft_mp3dec \
    libstagefright_soft_mpeg2dec \
    libstagefright_soft_mpeg4dec \
    libstagefright_soft_mpeg4enc \
    libstagefright_soft_opusdec \
    libstagefright_soft_rawdec \
    libstagefright_soft_vorbisdec \
    libstagefright_soft_vpxdec \
    libstagefright_soft_vpxenc \
    libstr_capture_interface \
    libstr_preview_interface \
    libstreamparser \
    libsuper_night_interface \
    libsurround_3mic_proc \
    libvideoutils \
    libvorbisidec \
    libvpx \
    libwfdaac_vendor \
    libwvhidl \
    libwvdrmengine \
    vendor.qti.hardware.audiohalext@1.0 \
    gatekeeper.mdfpp \
    keystore.mdfpp \
    libFacialStickerEngine.arcsoft \
    libflicker \
    libhexagon_nn_stub \
    libkeymaster2_mdfpp \
    libkeymaster_helper_vendor \
    liblearningmodule \
    libloadalgo_stub \
    libmdmimgload \
    libmeters \
    libnanopb \
    libnlnetmgr \
    libqdma_file_agent \
    libreffeature \
    libtzcom \
    libucsengine \
    libvkservice \
    unnhal-acc-adreno \
    unnhal-acc-common \
    unnhal-acc-hvx \
    vendor.qti.hardware.radio.atcmdfwd@1.0 \
    vendor.samsung.hardware.health@1.0 \
    vendor.trustonic.tee@1.0 \
    vendor.trustonic.teeregistry@1.0 \
    vendor_lib_rfsa_adsp_libVC1Dec_so \
    vendor_lib_rfsa_adsp_libVC1DecDsp_skel_so \
    vendor_lib_rfsa_adsp_libapps_mem_heap_so \
    vendor_lib_rfsa_adsp_libcvpdsp_skel_so \
    vendor_lib_rfsa_adsp_libdspCV_skel_so \
    vendor_lib_rfsa_adsp_libdsp_streamer_skel_so \
    vendor_lib_rfsa_adsp_libfastcvadsp_so \
    vendor_lib_rfsa_adsp_libfastcvdsp_skel_so \
    vendor_lib_rfsa_adsp_libhexagon_nn_skel_so \
    vendor_lib_rfsa_adsp_libsns_device_mode_skel_so \
    vendor_lib_rfsa_adsp_libsns_low_lat_stream_skel_so \
    com.quicinc.cne.api@1.0 \
    com.quicinc.cne.api@1.1 \
    com.quicinc.cne.constants@1.0 \
    com.quicinc.cne.constants@2.0 \
    com.quicinc.cne.constants@2.1 \
    vendor.qti.data.factory@1.0 \
    vendor.qti.hardware.data.iwlan@1.0 \
    ATFWD-daemon \
    PktRspTest \
    StoreKeybox \
    adpl \
    adsprpcd \
    argosd \
    audioflacapp \
    cdsprpcd \
    cplay \
    diag_callback_sample \
    diag_dci_sample \
    diag_klog \
    diag_mdlog \
    diag_socket_log \
    diag_uart_log \
    factory.ssc \
    fmconfig \
    fmfactorytest \
    fmfactorytestserver \
    hdcp1prov \
    hdcp2p2prov \
    hvdcp_opti \
    android.hardware.atrace@1.0-service \
    android.hardware.drm@1.2-service.clearkey \
    android.hardware.drm@1.2-service.widevine \
    android.hardware.gnss@2.0-service-qti \
    android.hardware.health@2.0-service.samsung \
    android.hardware.neuralnetworks@1.2-service-qti \
    android.hardware.vr@1.0-service \
    capabilityconfigstoretest \
    macloader \
    mfgloader \
    rild \
    vendor.qti.hardware.cryptfshw@1.0-service-qti \
    vendor.qti.hardware.cvp@1.0-service \
    vendor.qti.hardware.display.allocator@1.0-service \
    vendor.qti.hardware.iop@2.0-service \
    vendor.qti.hardware.perf@2.0-service \
    vendor.qti.hardware.qdutils_disp@1.0-service-qti \
    vendor.qti.hardware.qseecom@1.0-service \
    vendor.qti.hardware.tui_comm@1.0-service-qti \
    vendor.trustonic.tee@1.0-service \
    vendor.trustonic.teeregistry@1.0-service \
    wldu \
    ipacm-diag \
    irsc_util \
    loadalgo \
    loc_launcher \
    lowi-server \
    mcDriverDaemon \
    mdm_helper \
    mdm_helper_proxy \
    netmgrd \
    pd-mapper \
    pm-proxy \
    pm-service \
    pm_proxy_helper \
    port-bridge \
    ppd \
    pvclicense_sample \
    qdcmss \
    qseecom_sample_client \
    qseecomd \
    rmt_storage \
    secril_config_svc \
    secure_ui_sample_client \
    seemp_healthd \
    snap_utility_32 \
    snap_utility_64 \
    sscrpcd \
    ssr_diag \
    ssr_setup \
    subsystem_ramdump \
    tbaseLoader \
    test_diag \
    test_model.json \
    tftp_server \
    thermal-engine \
    time_client \
    time_daemon \
    vppservice \
    wvkprov \
    xtra-daemon

PRODUCT_PACKAGES += \
    vendor_lib_egl_libEGL_adreno_so \
    vendor_lib_egl_libGLESv2_adreno_so \
    vendor_lib_egl_libq3dtools_adreno_so \
    vendor_lib64_egl_libEGL_adreno_so \
    vendor_lib64_egl_libGLESv2_adreno_so \
    vendor_lib64_egl_libq3dtools_adreno_so
